
services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pgvectordb
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
